/**
 * Per-head offset nudges for 3D GLB models.
 *
 * Base offset is (0, -27, -0.25). Each nudge record adds to that base.
 * Values are eyeballed against 2D sprite counterparts.
 *
 * Y: positive = up   X: positive = right   Z: positive = forward (toward viewer)
 */

export const HEAD_Y_NUDGE: Record<string, number> = {
  // ── bottomRow 20 (majority) ──
  aardvark: 1,
  abstract: 1,
  ape: 1,
  bag: 1,
  bagpipe: 1,
  banana: 1,
  bat: 1,
  bear: 1,
  beer: 1,
  beet: 1,
  bell: 1,
  bigfoot: 1,
  'bigfoot-yeti': 1,
  boot: 1,
  bomb: 1,
  box: 1,
  boxingglove: 1,
  brain: 1,
  'burger-dollarmenu': 1,
  cake: 1,
  calculator: 1,
  calendar: 1,
  camcorder: 1,
  cannedham: 1,
  capybara: 1,
  car: 1,
  'cash-register': 1,
  cat: 1,
  'chart-bars': 1,
  chefhat: 1,
  cheese: 1,
  chicken: 1,
  chipboard: 1,
  chocolate: 1,
  cloud: 1,
  clutch: 1,
  cone: 1,
  'console-handheld': 1,
  cordlessphone: 1,
  cookie: 1,
  cottonball: 1,
  cow: 1,
  crab: 1,
  crane: 1,
  croc: 1,
  crown: 1,
  'crt-bsod': 1,
  crystalball: 1,
  'diamond-red': 1,
  dictionary: 1,
  dog: 1,
  drill: 1,
  duck: 1,
  ducky: 1,
  faberge: 1,
  fan: 1,
  fence: 1,
  'film-35mm': 1,
  'film-strip': 1,
  firehydrant: 1,
  flamingo: 1,
  fox: 1,
  frog: 1,
  garlic: 1,
  gavel: 1,
  gnome: 1,
  goldcoin: 1,
  goldfish: 1,
  grouper: 1,
  hair: 1,
  hanger: 1,
  hardhat: 1,
  helicopter: 1,
  hotdog: 1,
  igloo: 1,
  'index-card': 1,
  island: 1,
  kangaroo: 1,
  ketchup: 1,
  laptop: 1,
  lips: 1,
  lock: 1,
  macaroni: 1,
  mailbox: 1,
  maze: 1,
  milk: 1,
  mirror: 1,
  mixer: 1,
  mosquito: 1,
  mouse: 1,
  mug: 1,
  mustard: 1,
  nigiri: 1,
  noodles: 1,
  onion: 1,
  orca: 1,
  orangutan: 1,
  otter: 1,
  owl: 1,
  oyster: 1,
  paintbrush: 1,
  panda: 1,
  paperclip: 1,
  peyote: 1,
  pie: 1,
  piggybank: 1,
  pill: 1,
  pineapple: 1,
  pipe: 1,
  pirateship: 1,
  pizza: 1,
  plane: 1,
  pop: 1,
  porkbao: 1,
  pumpkin: 1,
  pyramid: 1,
  queencrown: 1,
  rabbit: 1,
  rainbow: 1,
  rangefinder: 1,
  raven: 1,
  retainer: 1,
  ring: 1,
  road: 1,
  robot: 1,
  rock: 1,
  safe: 1,
  saguaro: 1,
  sailboat: 1,
  sandwich: 1,
  saw: 1,
  scorpion: 1,
  shark: 1,
  shower: 1,
  'skeleton-hat': 1,
  skilift: 1,
  smile: 1,
  snowglobe: 1,
  snowman: 1,
  spaghetti: 1,
  spam: 1,
  sponge: 1,
  squid: 1,
  stapler: 1,
  sunset: 1,
  sushi: 1,
  taxi: 1,
  thumbsup: 1,
  trashcan: 1,
  turing: 1,
  undead: 1,
  unicorn: 1,
  'vending-machine': 1,
  vent: 1,
  void: 1,
  wallet: 1,
  wallsafe: 1,
  washingmachine: 1,
  wave: 1,
  weight: 1,
  werewolf: 1,
  wine: 1,
  wizardhat: 1,
  zebra: 1,

  // ── bottomRow 21 ──
  bank: 1,
  bonsai: 1,
  cherry: 1,
  couch: 1,
  'croc-hat': 1,
  dino: 1,
  hockeypuck: 1,
  'horse-deepfried': 1,
  house: 1,
  moose: 1,
  mushroom: 1,
  piano: 1,
  pickle: 1,
  potato: 1,
  'ruler-triangular': 1,
  snowmobile: 1,
  tornado: 1,
  treasurechest: 1,
  ufo: 1,
  volcano: 1,
  volleyball: 1,
  wall: 1,
  watch: 1,
  watermelon: 1,
  weed: 1,
  'whale-alive': 1,

  // ── bottomRow 22 ──
  basketball: 1,
  'bubble-speech': 1,
  chainsaw: 1,
  chameleon: 1,
  clover: 1,
  coffeebean: 1,
  dna: 1,
  doughnut: 1,
  earth: 1,
  moon: 1,
  peanut: 1,
  pillow: 1,
  pufferfish: 1,
  rgb: 1,
  saturn: 1,
  steak: 1,
  whale: 1,

  // ── bottomRow 23 ──
  blackhole: 1,
  bubblegum: 1,
  heart: 1,
  tooth: 1,

  // ── bottomRow 24 ──
  'diamond-blue': 1,
  fir: 1,
  flower: 1,
  goat: 1,

  // ── bottomRow 25 ──
  chips: 1,
  'lightning-bolt': 1,

  // ── outliers (eyeballed) ──
  lint: 2,
  cd: -1,
  chain: -1,
  outlet: -1,
  blueberry: -2,
  jupiter: -4,

  // ── bottomRow 31 ──
  boombox: 1,
  microwave: 1,
  toaster: 1,
  'wine-barrel': 1,
};

export const HEAD_X_NUDGE: Record<string, number> = {
  bagpipe: 1,
  calendar: -1,
  'cash-register': 1,
  jellyfish: 1,
  zebra: 2,
};

/** Z: positive = forward (toward viewer) */
export const HEAD_Z_NUDGE: Record<string, number> = {
  camcorder: 2,
  'film-strip': 1,
  fox: 1,
  mirror: 1,
  noodles: 1,
  pipe: 1,
  pineapple: 1,
  pirateship: 1,
  skilift: 1,
  wine: 1,
};

/** Base offset applied to all GLB heads before per-head nudges */
export const HEAD_BASE_OFFSET: [number, number, number] = [0, -27, -0.25];

/** Compute the full offset for a given head trait name */
export function getHeadOffset(traitName: string): [number, number, number] {
  return [
    HEAD_BASE_OFFSET[0] + (HEAD_X_NUDGE[traitName] ?? 0),
    HEAD_BASE_OFFSET[1] + (HEAD_Y_NUDGE[traitName] ?? 0),
    HEAD_BASE_OFFSET[2] + (HEAD_Z_NUDGE[traitName] ?? 0),
  ];
}
