import type { VoxelMap } from './types';
import { parseKey } from './voxelMap';

/**
 * Export VoxelMap as OBJ format string.
 * Each voxel becomes a unit cube at its grid position.
 * Suitable for 3D printing after import into slicer software.
 */
export function toOBJ(map: VoxelMap): string {
  const lines: string[] = ['# Noun Voxel Export', '# Generated by @nouns/voxel-engine', ''];
  let vertexOffset = 0;

  for (const [key, color] of map) {
    const [x, y, z] = parseKey(key);
    // Unit cube centered at (x, y, z)
    const cx = x - 15.5;
    const cy = y - 15.5;
    const cz = z;
    const h = 0.5;

    // 8 vertices of a unit cube
    lines.push(`# voxel ${key} ${color}`);
    lines.push(`v ${cx - h} ${cy - h} ${cz - h}`);
    lines.push(`v ${cx + h} ${cy - h} ${cz - h}`);
    lines.push(`v ${cx + h} ${cy + h} ${cz - h}`);
    lines.push(`v ${cx - h} ${cy + h} ${cz - h}`);
    lines.push(`v ${cx - h} ${cy - h} ${cz + h}`);
    lines.push(`v ${cx + h} ${cy - h} ${cz + h}`);
    lines.push(`v ${cx + h} ${cy + h} ${cz + h}`);
    lines.push(`v ${cx - h} ${cy + h} ${cz + h}`);

    // 6 faces (quads)
    const o = vertexOffset;
    lines.push(`f ${o + 1} ${o + 2} ${o + 3} ${o + 4}`); // back
    lines.push(`f ${o + 5} ${o + 8} ${o + 7} ${o + 6}`); // front
    lines.push(`f ${o + 1} ${o + 5} ${o + 6} ${o + 2}`); // bottom
    lines.push(`f ${o + 3} ${o + 7} ${o + 8} ${o + 4}`); // top
    lines.push(`f ${o + 1} ${o + 4} ${o + 8} ${o + 5}`); // left
    lines.push(`f ${o + 2} ${o + 6} ${o + 7} ${o + 3}`); // right

    vertexOffset += 8;
  }

  return lines.join('\n');
}

/**
 * Export VoxelMap as binary STL.
 * Returns an ArrayBuffer suitable for download as .stl file.
 */
export function toSTL(map: VoxelMap): ArrayBuffer {
  // Each voxel = 6 faces = 12 triangles
  const numTriangles = map.size * 12;
  const bufferSize = 80 + 4 + numTriangles * 50;
  const buffer = new ArrayBuffer(bufferSize);
  const view = new DataView(buffer);

  // Header (80 bytes)
  const header = 'Noun Voxel STL - @nouns/voxel-engine';
  for (let i = 0; i < Math.min(header.length, 80); i++) {
    view.setUint8(i, header.charCodeAt(i));
  }

  // Triangle count
  view.setUint32(80, numTriangles, true);

  let offset = 84;
  const writeTriangle = (
    nx: number, ny: number, nz: number,
    v1: number[], v2: number[], v3: number[],
  ) => {
    // Normal
    view.setFloat32(offset, nx, true); offset += 4;
    view.setFloat32(offset, ny, true); offset += 4;
    view.setFloat32(offset, nz, true); offset += 4;
    // Vertices
    for (const v of [v1, v2, v3]) {
      view.setFloat32(offset, v[0], true); offset += 4;
      view.setFloat32(offset, v[1], true); offset += 4;
      view.setFloat32(offset, v[2], true); offset += 4;
    }
    // Attribute byte count
    view.setUint16(offset, 0, true); offset += 2;
  };

  for (const [key] of map) {
    const [x, y, z] = parseKey(key);
    const cx = x - 15.5;
    const cy = y - 15.5;
    const cz = z;
    const h = 0.5;

    const v = [
      [cx - h, cy - h, cz - h], // 0: left-bottom-back
      [cx + h, cy - h, cz - h], // 1: right-bottom-back
      [cx + h, cy + h, cz - h], // 2: right-top-back
      [cx - h, cy + h, cz - h], // 3: left-top-back
      [cx - h, cy - h, cz + h], // 4: left-bottom-front
      [cx + h, cy - h, cz + h], // 5: right-bottom-front
      [cx + h, cy + h, cz + h], // 6: right-top-front
      [cx - h, cy + h, cz + h], // 7: left-top-front
    ];

    // Back face (-Z)
    writeTriangle(0, 0, -1, v[0], v[2], v[1]);
    writeTriangle(0, 0, -1, v[0], v[3], v[2]);
    // Front face (+Z)
    writeTriangle(0, 0, 1, v[4], v[5], v[6]);
    writeTriangle(0, 0, 1, v[4], v[6], v[7]);
    // Bottom (-Y)
    writeTriangle(0, -1, 0, v[0], v[1], v[5]);
    writeTriangle(0, -1, 0, v[0], v[5], v[4]);
    // Top (+Y)
    writeTriangle(0, 1, 0, v[3], v[7], v[6]);
    writeTriangle(0, 1, 0, v[3], v[6], v[2]);
    // Left (-X)
    writeTriangle(-1, 0, 0, v[0], v[4], v[7]);
    writeTriangle(-1, 0, 0, v[0], v[7], v[3]);
    // Right (+X)
    writeTriangle(1, 0, 0, v[1], v[2], v[6]);
    writeTriangle(1, 0, 0, v[1], v[6], v[5]);
  }

  return buffer;
}

/** Trigger browser download of a file. */
export function downloadBlob(data: ArrayBuffer | string, filename: string, mime: string) {
  const blob = new Blob([data], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}
