// ─── Agent NounIRL — Autonomous Deployer ────────────────────────────────────
//
// Uses Claude API to generate code patches and ships them to a fixed
// non-production Netlify deploy. The agent never touches `main`/prod — pip
// reviews the live `dev-noun` preview and merges to main manually.
//
// Trust model:
// - Code is generated by an LLM that may be prompt-injected via terminal chat,
//   so every patch is treated as untrusted input. Layers of defence:
//     1. Path allowlist  (DEPLOY_ALLOWED_PATHS)        — only nouns-webapp/src
//     2. Path denylist   (DEPLOY_DENY_PATH_SUFFIXES)   — never config/router/entry files
//     3. Action denylist                                — `delete` actions are forbidden
//     4. Source denylist (DEPLOY_DENY_SOURCE_PATTERNS) — eval/<script src>/etc.
//     5. Size caps       (DEPLOY_MAX_PATCH_*)
//     6. Branch pin      (DEPLOY_BASE_BRANCH = 'dev-noun') — never touches main
//     7. Production isolation — `dev-noun` is the ONLY branch the agent writes
//        to. Netlify ships `dev-noun` to a non-prod URL. Production builds
//        from `main`, which the agent has no path to push to.
// - When the deploy succeeds, the agent's response includes the dev-noun URL
//   and instructs the user to DM pip for review/promotion to prod.

import {
  MAX_DEPLOYS_PER_HOUR,
  DEPLOY_ALLOWED_PATHS,
  DEPLOY_BASE_BRANCH,
  DEV_NOUN_URL,
  DEPLOY_MAX_PATCH_FILES,
  DEPLOY_MAX_PATCH_BYTES,
  DEPLOY_DENY_PATH_SUFFIXES,
  DEPLOY_DENY_SOURCE_PATTERNS,
} from './constants.js';
import { hubGenerate } from './hubClient.js';

// ─── Types ─────────────────────────────────────────────────────────────────

export interface FilePatch {
  path: string; // relative to repo root, e.g. "packages/nouns-webapp/src/components/Foo.tsx"
  action: 'create' | 'modify' | 'delete';
  content?: string; // full file content for create/modify
}

export interface DeployResult {
  success: boolean;
  error?: string;
  branch?: string;
  commitSha?: string;
  /** Netlify deploy admin URL (where the build is queued/done). */
  deployUrl?: string;
  /** Stable preview URL where the change is visible to users. */
  previewUrl?: string;
  patches: FilePatch[];
  timestamp: number;
  reason: string;
}

interface DeployRecord {
  id: string;
  result: DeployResult;
  triggeredBy: string; // 'settlement' | 'terminal' | 'scheduled'
}

// ─── State ─────────────────────────────────────────────────────────────────

const deployHistory: DeployRecord[] = [];
let lastDeployTime = 0;

// ─── Path Validation ───────────────────────────────────────────────────────

function isAllowedPath(path: string): boolean {
  return DEPLOY_ALLOWED_PATHS.some(prefix => path.startsWith(prefix));
}

// ─── Patch Safety ──────────────────────────────────────────────────────────
//
// Throws on any patch that fails defence-in-depth checks. Order matters:
// cheap structural checks first, then per-file path/content scans. Throwing
// (rather than returning a result) lets `applyAndDeploy` log a single
// `error` field with the full reason — no GitHub side-effects happen yet
// because this runs before the first API call.

function assertPatchesSafe(patches: FilePatch[]): void {
  if (patches.length === 0) {
    throw new Error('safety: no patches to apply');
  }
  if (patches.length > DEPLOY_MAX_PATCH_FILES) {
    throw new Error(
      `safety: ${patches.length} files exceeds DEPLOY_MAX_PATCH_FILES (${DEPLOY_MAX_PATCH_FILES})`,
    );
  }

  let totalBytes = 0;
  for (const patch of patches) {
    // Allow-list (already enforced in generatePatch, but cheap to repeat —
    // direct callers of applyAndDeploy might bypass generatePatch).
    if (!isAllowedPath(patch.path)) {
      throw new Error(`safety: path not in allowlist: ${patch.path}`);
    }

    // Deny-list — critical entry/config/wallet files.
    for (const suffix of DEPLOY_DENY_PATH_SUFFIXES) {
      if (patch.path.endsWith(suffix)) {
        throw new Error(`safety: path on denylist (${suffix}): ${patch.path}`);
      }
    }

    // The agent is additive only — it can create or modify files, never
    // delete them. Removes the entire class of "agent wipes the codebase"
    // failure modes (prompt injection, hallucination, malicious user) and
    // means rollback is always a `git revert`, never a "where did this file
    // go" investigation.
    if (patch.action === 'delete') {
      throw new Error(`safety: delete actions are not permitted (path: ${patch.path})`);
    }
    const content = patch.content ?? '';
    totalBytes += content.length;

    // Per-file source pattern deny.
    for (const { re, reason } of DEPLOY_DENY_SOURCE_PATTERNS) {
      const match = content.match(re);
      if (match) {
        throw new Error(
          `safety: forbidden pattern in ${patch.path} (${reason}): ${match[0].slice(0, 80)}`,
        );
      }
    }
  }

  if (totalBytes > DEPLOY_MAX_PATCH_BYTES) {
    throw new Error(
      `safety: total patch size ${totalBytes}B exceeds DEPLOY_MAX_PATCH_BYTES (${DEPLOY_MAX_PATCH_BYTES})`,
    );
  }
}

// ─── Generate Code Patch via Claude API ────────────────────────────────────

export async function generatePatch(
  description: string,
  context: Record<string, unknown> = {},
): Promise<FilePatch[]> {
  const systemPrompt = `You are Agent NounIRL's code generation module. You generate precise, minimal code patches for the noun.wtf frontend (a Vite + React + TypeScript webapp).

RULES:
- Only output JSON — an array of file patches
- Each patch: { "path": "packages/nouns-webapp/src/...", "action": "create"|"modify"|"delete", "content": "..." }
- Only modify files under packages/nouns-webapp/src/
- Keep changes minimal and focused
- Match existing code style (TypeScript, inline styles, React functional components)
- Never break the build — all TypeScript must compile

Output ONLY valid JSON array, no markdown fences, no explanation.`;

  const text = await hubGenerate({
    system: systemPrompt,
    user: `Generate a code patch for the following change:\n\n${description}\n\nContext: ${JSON.stringify(context, null, 2)}\n\nReturn a JSON array of FilePatch objects.`,
    task: 'codeGen',
    maxTokens: 4096,
    temperature: 0.3,
  });

  // Parse JSON response
  const patches = JSON.parse(text) as FilePatch[];

  // Validate all paths
  for (const patch of patches) {
    if (!isAllowedPath(patch.path)) {
      throw new Error(`Patch path not allowed: ${patch.path}`);
    }
  }

  return patches;
}

// ─── GitHub API Operations ─────────────────────────────────────────────────

async function githubApi(
  endpoint: string,
  method: string = 'GET',
  body?: unknown,
): Promise<unknown> {
  const token = process.env.GITHUB_TOKEN;
  if (!token) throw new Error('GITHUB_TOKEN not configured');

  const repo = process.env.GITHUB_REPO || 'mshrmstudio/noun-wtf';
  const url = `https://api.github.com/repos/${repo}${endpoint}`;

  const res = await fetch(url, {
    method,
    headers: {
      Authorization: `Bearer ${token}`,
      Accept: 'application/vnd.github.v3+json',
      'Content-Type': 'application/json',
    },
    body: body ? JSON.stringify(body) : undefined,
  });

  if (!res.ok) {
    const errText = await res.text();
    throw new Error(`GitHub API error: ${res.status} ${errText}`);
  }

  return res.json();
}

/**
 * Create a branch, commit patches, push, and optionally trigger Netlify deploy.
 */
export async function applyAndDeploy(
  patches: FilePatch[],
  commitMessage: string,
  reason: string,
  triggeredBy: string = 'agent',
): Promise<DeployResult> {
  const now = Date.now();

  // Rate limit check
  if (now - lastDeployTime < 3600_000 / MAX_DEPLOYS_PER_HOUR) {
    const result: DeployResult = {
      success: false,
      error: `Rate limited — max ${MAX_DEPLOYS_PER_HOUR} deploy(s) per hour`,
      patches,
      timestamp: now,
      reason,
    };
    recordDeploy(result, triggeredBy);
    return result;
  }

  // Safety: structural + content checks before ANY GitHub mutation.
  try {
    assertPatchesSafe(patches);
  } catch (err) {
    const result: DeployResult = {
      success: false,
      error: err instanceof Error ? err.message : String(err),
      patches,
      timestamp: now,
      reason,
    };
    recordDeploy(result, triggeredBy);
    console.error('[NounIRL] Deploy blocked by safety check:', result.error);
    return result;
  }

  try {
    // 1. Get the dev-noun branch's latest commit SHA. The agent only ever
    //    appends to this branch — never to main, never to a feature branch.
    //    If `dev-noun` is missing on the remote, the GitHub API 404s here
    //    and the deploy aborts (fail-closed).
    const ref = (await githubApi(`/git/ref/heads/${DEPLOY_BASE_BRANCH}`)) as {
      object: { sha: string };
    };
    const baseSha = ref.object.sha;

    // 2. Get the base tree from the current dev-noun tip.
    const baseCommit = (await githubApi(`/git/commits/${baseSha}`)) as { tree: { sha: string } };
    const baseTreeSha = baseCommit.tree.sha;

    // 3. Create blobs for each file. `delete` actions are rejected upstream
    //    by `assertPatchesSafe`, so every patch here is create or modify.
    const treeItems: Array<{
      path: string;
      mode: string;
      type: string;
      sha?: string;
      content?: string;
    }> = [];

    for (const patch of patches) {
      const blob = (await githubApi('/git/blobs', 'POST', {
        content: patch.content,
        encoding: 'utf-8',
      })) as { sha: string };

      treeItems.push({
        path: patch.path,
        mode: '100644',
        type: 'blob',
        sha: blob.sha,
      });
    }

    // 4. Create tree
    const tree = (await githubApi('/git/trees', 'POST', {
      base_tree: baseTreeSha,
      tree: treeItems,
    })) as { sha: string };

    // 5. Create commit
    const commit = (await githubApi('/git/commits', 'POST', {
      message: `[NounIRL] ${commitMessage}\n\nAutonomous deploy by Agent NounIRL\nReason: ${reason}`,
      tree: tree.sha,
      parents: [baseSha],
    })) as { sha: string };

    // 6. Fast-forward dev-noun to the new commit. If someone else (pip,
    //    another agent run) raced ahead and dev-noun has moved past
    //    `baseSha`, this PATCH will fail with a non-fast-forward error and
    //    the deploy aborts cleanly — better than force-pushing over their
    //    work. The next deploy attempt will pick up the new tip.
    await githubApi(`/git/refs/heads/${DEPLOY_BASE_BRANCH}`, 'PATCH', {
      sha: commit.sha,
      force: false,
    });

    // 7. Trigger the Netlify branch-deploy for `dev-noun`. Always fires —
    //    the production isolation is structural (different branch, different
    //    Netlify deploy context), not behavioural. There's no env gate,
    //    because flipping a flag should never be the only thing standing
    //    between the agent and prod. Even if NETLIFY_BUILD_HOOK were
    //    misconfigured to a prod hook, the agent's commits aren't on `main`
    //    so the prod build wouldn't pick them up.
    const netlifyHook = process.env.NETLIFY_BUILD_HOOK;
    if (netlifyHook) {
      try {
        await fetch(netlifyHook, { method: 'POST' });
      } catch (err) {
        console.error('[NounIRL] Netlify deploy hook failed:', err);
      }
    }

    lastDeployTime = now;

    const result: DeployResult = {
      success: true,
      branch: DEPLOY_BASE_BRANCH,
      commitSha: commit.sha,
      previewUrl: DEV_NOUN_URL,
      patches,
      timestamp: now,
      reason,
    };

    recordDeploy(result, triggeredBy);
    console.log(
      `[NounIRL] ✅ Deploy successful — branch: ${DEPLOY_BASE_BRANCH}, commit: ${commit.sha}, preview: ${DEV_NOUN_URL}`,
    );
    return result;
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    console.error('[NounIRL] Deploy failed:', msg);

    const result: DeployResult = {
      success: false,
      error: msg,
      patches,
      timestamp: now,
      reason,
    };

    recordDeploy(result, triggeredBy);
    return result;
  }
}

// ─── Deploy History ────────────────────────────────────────────────────────

function recordDeploy(result: DeployResult, triggeredBy: string): void {
  deployHistory.push({
    id: crypto.randomUUID(),
    result,
    triggeredBy,
  });

  // Keep last 100 deploys
  if (deployHistory.length > 100) {
    deployHistory.splice(0, deployHistory.length - 100);
  }
}

export function getDeployHistory(limit = 20): DeployRecord[] {
  return deployHistory.slice(-limit).reverse();
}

export function canDeploy(): boolean {
  return Date.now() - lastDeployTime >= 3600_000 / MAX_DEPLOYS_PER_HOUR;
}
