import { Address, Bytes, BigInt } from '@graphprotocol/graph-ts';
import { ProposalCreatedWithRequirements, ProposalCreatedWithRequirements1, VoteCast, MinQuorumVotesBPSSet, MaxQuorumVotesBPSSet, QuorumCoefficientSet, ProposalObjectionPeriodSet, ProposalUpdated, ProposalDescriptionUpdated, ProposalTransactionsUpdated, EscrowedToFork, WithdrawFromForkEscrow, ProposalCanceled, ProposalVetoed, ProposalExecuted, ProposalQueued, ProposalCreated } from '../src/types/NounsDAO/NounsDAO';
import { ProposalCandidateCreated, SignatureAdded } from '../src/types/NounsDAOData/NounsDAOData';
import { DelegateChanged, DelegateVotesChanged, Transfer } from '../src/types/NounsToken/NounsToken';
export declare function createProposalCreatedWithRequirementsEventV3(input: ProposalCreatedWithRequirementsEvent): ProposalCreatedWithRequirements;
export declare class ProposalCreatedWithRequirementsEvent {
    id: BigInt;
    proposer: Address;
    signers: Address[];
    targets: Address[];
    values: BigInt[];
    signatures: string[];
    calldatas: Bytes[];
    startBlock: BigInt;
    endBlock: BigInt;
    updatePeriodEndBlock: BigInt;
    proposalThreshold: BigInt;
    quorumVotes: BigInt;
    description: string;
    eventBlockNumber: BigInt;
}
export declare function createProposalCreatedWithRequirementsEventV1(input: ProposalCreatedWithRequirementsEvent): ProposalCreatedWithRequirements1;
export declare function stubProposalCreatedWithRequirementsEventInput(eventBlockNumber?: BigInt, signers?: Address[]): ProposalCreatedWithRequirementsEvent;
export declare function createVoteCastEvent(voter: Address, proposalId: BigInt, support: i32, votes: BigInt): VoteCast;
export declare function createMinQuorumVotesBPSSetEvent(oldMinQuorumVotesBPS: i32, newMinQuorumVotesBPS: i32): MinQuorumVotesBPSSet;
export declare function createMaxQuorumVotesBPSSetEvent(oldMaxQuorumVotesBPS: i32, newMaxQuorumVotesBPS: i32): MaxQuorumVotesBPSSet;
export declare function createQuorumCoefficientSetEvent(oldQuorumCoefficient: BigInt, newQuorumCoefficient: BigInt): QuorumCoefficientSet;
export declare function handleAllQuorumParamEvents(newMinQuorumVotesBPS: i32, newMaxQuorumVotesBPS: i32, newCoefficient: BigInt): void;
export declare function createProposalObjectionPeriodSetEvent(proposalId: BigInt, objectionPeriodEndBlock: BigInt): ProposalObjectionPeriodSet;
export declare function createProposalUpdatedEvent(txHash: Bytes, logIndex: BigInt, blockTimestamp: BigInt, blockNumber: BigInt, proposalId: BigInt, proposer: Address, targets: Address[], values: BigInt[], signatures: string[], calldatas: Bytes[], description: string, updateMessage: string): ProposalUpdated;
export declare function createProposalCandidateCreatedEvent(txHash: Bytes, logIndex: BigInt, blockTimestamp: BigInt, blockNumber: BigInt, sender: Address, targets: Address[], values: BigInt[], signatures: string[], calldatas: Bytes[], description: string, slug: string, encodedProposalHash: Bytes): ProposalCandidateCreated;
export declare function createSignatureAddedEvent(signer: Address, sig: Bytes, expirationTimestamp: BigInt, proposer: Address, slug: string, encodedPropHash: Bytes, sigDigest: Bytes, reason: string, blockNumber: BigInt, blockTimestamp: BigInt): SignatureAdded;
export declare function createProposalDescriptionUpdatedEvent(txHash: Bytes, logIndex: BigInt, blockTimestamp: BigInt, blockNumber: BigInt, proposalId: BigInt, proposer: Address, description: string, updateMessage: string): ProposalDescriptionUpdated;
export declare function createProposalTransactionsUpdatedEvent(txHash: Bytes, logIndex: BigInt, blockTimestamp: BigInt, blockNumber: BigInt, proposalId: BigInt, proposer: Address, targets: Address[], values: BigInt[], signatures: string[], calldatas: Bytes[], updateMessage: string): ProposalTransactionsUpdated;
export declare function createEscrowedToForkEvent(txHash: Bytes, logIndex: BigInt, blockTimestamp: BigInt, owner: Address, tokenIds: Array<BigInt>, proposalIds: Array<BigInt>, reason: string, forkId: BigInt): EscrowedToFork;
export declare function createWithdrawFromForkEscrowEvent(txHash: Bytes, logIndex: BigInt, blockTimestamp: BigInt, owner: Address, tokenIds: Array<BigInt>, forkId: BigInt): WithdrawFromForkEscrow;
export declare function createProposalCanceledEvent(txHash: Bytes, logIndex: BigInt, blockTimestamp: BigInt, blockNumber: BigInt, proposalId: BigInt): ProposalCanceled;
export declare function createProposalVetoedEvent(txHash: Bytes, logIndex: BigInt, blockTimestamp: BigInt, blockNumber: BigInt, proposalId: BigInt): ProposalVetoed;
export declare function createProposalExecutedEvent(txHash: Bytes, logIndex: BigInt, blockTimestamp: BigInt, blockNumber: BigInt, proposalId: BigInt): ProposalExecuted;
export declare function createProposalQueuedEvent(txHash: Bytes, logIndex: BigInt, blockTimestamp: BigInt, blockNumber: BigInt, proposalId: BigInt, eta: BigInt): ProposalQueued;
export declare function createTransferEvent(txHash: Bytes, logIndex: BigInt, blockTimestamp: BigInt, blockNumber: BigInt, from: Address, to: Address, tokenId: BigInt): Transfer;
export declare function createDelegateChangedEvent(txHash: Bytes, logIndex: BigInt, blockTimestamp: BigInt, blockNumber: BigInt, delegator: Address, previousDelegate: Address, newDelegate: Address): DelegateChanged;
export declare function createDelegateVotesChangedEvent(txHash: Bytes, logIndex: BigInt, blockTimestamp: BigInt, blockNumber: BigInt, delegate: Address, previousBalance: BigInt, newBalance: BigInt): DelegateVotesChanged;
export declare class ProposalCreatedData {
    id: BigInt;
    proposer: Address;
    signers: Address[];
    targets: Address[];
    values: BigInt[];
    signatures: string[];
    calldatas: Bytes[];
    startBlock: BigInt;
    endBlock: BigInt;
    description: string;
    eventBlockNumber: BigInt;
    eventBlockTimestamp: BigInt;
    txHash: Bytes;
    logIndex: BigInt;
    address: Address;
}
export declare function createProposalCreatedEvent(input: ProposalCreatedData): ProposalCreated;
